# Generated by Django 2.1.3 on 2018-11-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload_name', models.CharField(max_length=100)),
                ('workload_model', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=400)),
                ('runtime', models.BigIntegerField()),
                ('machine_specs', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date_time',),
            },
        ),
    ]
