# Generated by Django 2.1.3 on 2018-11-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20181114_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='workload_name',
        ),
    ]
